### ISSUE TITLE
Cannot access '<init>': it is private in <ClassName>

### ISSUE THREAD

**Issue by mathieudebrito** [Kodein-Framework/MocKMP#11]
Dear MocKMP team,

I just came by your library, and it's pretty awesome ! 
I ran into a breaking issue using the library : when the data class constructor is private, the following issue is raised : 
`Cannot access '<init>': it is private in <ClassName>` 

I have a data class like this : 

```kotlin
data class Model (
val someInstant: kotlinx.datetime.Instant 
) 
```

When trying to use in tests : 
```kotlin
@UsesFakes(Model::class)
class ModelTests : TestsWithMocks(){
    override fun setUpMocks() = injectMocks(mocker)

    @Fake
    lateinit var model: Model

   ...
}
```

It generates something like this : 
```kotlin
internal fun fakeInstant() = Instant()
```

The problem is that `Instant` has private constructor.

Is there any way to add a default way to create fakes ?

Thank you !

**Comment by SalomonBrys** [comment]
Fixed in `1.4.0`.

See https://github.com/Kodein-Framework/MocKMP#providing-fake-instances
