### ISSUE TITLE
Usage of isEqual(otherMock) in verify {} causes verification of otherMock.toString()

### ISSUE THREAD

**Issue by lupuuss** [Kodein-Framework/MocKMP#13]
Whenever isEqual(...) (and similar matchers) is called inside verify {} with mocked argument,  it causes argument's toString() method verification.

```kotlin
    val sut = Sut(mock, otherMock)

    @Test
    fun test() {
        sut.process()
        verify { mock.foo(isEqual(otherMock)) } // Assertion error - Expected otherMock.toString() but not called
    }
```

It seems that isEqual(...) calls otherMock.toString() during ArgConstraint creation and it leads to unintended verification. I think it could be fixed by resolving ArgConstraint.description lazily.

P.S. I am not sure if this use case is fully valid, but I've encountered it inside my side project.

**Comment by SalomonBrys** [comment]
Fixed in 1.5.0 : https://github.com/Kodein-Framework/MocKMP/releases/tag/v1.5.0
