### ISSUE TITLE
Mocking a deprecated method generate warnings

### ISSUE THREAD

**Issue by glureau** [Kodein-Framework/MocKMP#16]
Given an interface with a `@Deprecated` method, if I mock this interface I'll get a warning message:

    w: /Users/...../MyInterface.kt: (98, 23): This declaration overrides deprecated member but not marked as deprecated itself. This deprecation won't be inherited in future releases. Please add @Deprecated annotation or suppress

It can be problematic when using warningAsErrors.

**Comment by SalomonBrys** [comment]
Fixed in 1.5.0 : https://github.com/Kodein-Framework/MocKMP/releases/tag/v1.5.0
