### ISSUE TITLE
Can't get injectMocks to work

### ISSUE THREAD

**Issue by Nailik** [Kodein-Framework/MocKMP#20]
Hi,
i see that ksp generation have to run once before `injectMocks` is available.
When i try to run my tests it runs `kspDebugUnitTestKotlinAndroid` is that the generation?

Because it can't find `injectMocks` method and the sentence in the docs
`This is mandatory and cannot be generated. You need to run the KSP generation at least once for your IDE to see the injectMocks generated function.`

doesn't describe how to run the KSP geneartion.

I use the quickstart setup in my gradle file but version 1.4.0 because the project uses kotlin 1.6.10

```
plugins {
    id("org.kodein.mock.mockmp") version "1.4.0"
}

mockmp {
    usesHelper = true
}
```

**Comment by SalomonBrys** [comment]
Running your test should trigger the build, which should trigger KSP.

`injectMocks` will only be generated for a class if that class contains at least one `@Mock` annotated property.
