### ISSUE TITLE
Compilation error with Kotlin 1.7.0-RC

### ISSUE THREAD

**Issue by anar110** [Kodein-Framework/MocKMP#25]
I get the following error when building with 1.7.0-RC version of Kotlin that was just released:

`ksp-1.6.21-1.0.5 is too old for kotlin-1.7.0-RC. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.6.21.`

Just reporting it as its still early days. I was just trying out the new memory model and iOS and couldn't get my project to build yet.

**Comment by HylkeB** [comment]
Kotlin 1.7.0 is now officially released but this library (or the MocKMP gradle plugin) is not yet compatible with the corresponding KSP version (which should be `1.7.0-1.0.6`)
